### ISSUE TITLE
Variables in build scripts

### ISSUE THREAD

**Issue by mmh352** [mmh352/ou-container-builder#18]
Just in passing, I also note that in my original Dockerfiles, the version (3.3) was assigned to a `VERSION` variable and referenced as such. Again, the current config does not support that, but I know from experience that if you leave version numbers in paths as literals, when you update a version it's all too easy to miss one!

_Originally posted by @psychemedia in https://github.com/mmh352/ou-container-builder/issues/11#issuecomment-832075036_

**Comment by mmh352** [comment]
Variables within an inline script will work. Variables within the ContainerConfig file currently don't work. It is an interesting suggestion. I think I would need to see a concrete example where that is needed.

The ideal safety net is of course to have some automated testing of the container.

**Comment by psychemedia** [comment]
Re: variables, another useful variable may something along the lines of the Jupyter official stack convention of `$NB_USER`, as discussed more in https://github.com/mmh352/ou-container-builder/issues/19.
